@hostname = localhost
@port = 7174
@base_url = https://{{hostname}}:{{port}}

###  שליחת עסקה חדשה
POST {{base_url}}/api/transactions
Content-Type: application/json

{
  "transactionId": "550e8400-e29b-41d4-a716-446655440000",
  "amount": 0,
  "currency": "USD",
  "status": "Completed",
  "timestamp": "2026-01-01T10:00:00Z"
}

### שלב ב: בדיקה שהעסקה נשמרה בזיכרון (GET)
GET {{base_url}}/api/transactions/recent
Accept: application/json
